import { Roboto, Roboto_Slab } from "next/font/google";
import "../styles/global.css";
import "../styles/nullstyle.css";
import Layout from "@/components/Layout";
import ImageErrorHandler from "@/misc/ImageErrorHandler";

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-default"
});

const robotoSlab = Roboto_Slab({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-accent"
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.variable} ${robotoSlab.variable}`}>
      <body className={`${roboto.className}`}>
        <ImageErrorHandler>
          <Layout >
            {children}
          </Layout>
        </ImageErrorHandler>
      </body>
    </html>
  )
}
