import { Roboto, Roboto_Slab } from "next/font/google";
import "@/styles/global.css";
import "@/styles/nullstyle.css";
import Head from "next/head";

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-default"
});

const robotoSlab = Roboto_Slab({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-accent"
});

export const metadata = {
  title: 'Ermakov frontend development',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.variable} ${robotoSlab.variable} !w-full overflow-hidden`}>
      <body className={`${roboto.className} leading-6`}>
        {children}
      </body>
    </html>
  )
}
